# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core


name: Azure Pipelines
variables:
  python.version: '3.7.6'
  buildConfiguration: 'Release'
stages:
- stage: Build
  jobs:
  - job:  Build
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
      - task: ServiceNow-DevOps-Agent-Job-Notification@1
        inputs:
          connectedServiceName: 'ServiceNowDevOps'
          Phase: 'STARTED'
      - script: dotnet build --configuration $(buildConfiguration)
        displayName: 'dotnet build $(buildConfiguration)'
      - task: ServiceNow-DevOps-Agent-Job-Notification@1
        inputs:
          connectedServiceName: 'ServiceNowDevOps'
          Phase: 'COMPLETED'
- stage: Deploy
  jobs:
  - job:  Deploy
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
      - task: ServiceNow-DevOps-Agent-Job-Notification@1
        inputs:
          connectedServiceName: 'ServiceNowDevOps'
          Phase: 'STARTED'
      - script: dotnet build --configuration $(buildConfiguration)
        displayName: 'dotnet build $(buildConfiguration)'
      - task: ServiceNow-DevOps-Agent-Job-Notification@1
        inputs:
          connectedServiceName: 'ServiceNowDevOps'
          Phase: 'COMPLETED'
     
